version: "3.9"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./config/
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./config:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE-NAME=postgres
      - DATABASE-USER=postgres
      - DATABASE-PASSWORD=postgres
      - DATABASE-HOST=database
      - DATABASE-PORT=5432
    depends_on:
      - database
      - redis
    restart: on-failure

  database:
    container_name: database
    image: postgres:16.0
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
    restart: on-failure

  redis:
    container_name: redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    command: sh -c "redis-server --save 60 1 --loglevel warning"
    restart: on-failure

  celery:
    container_name: celery
    image: celery
    build:
      context: ./config/
      dockerfile: Dockerfile
    command: sh -c "celery -A config worker -l INFO -Q celery,celery:1,celery:2,celery:3"
    volumes:
      - ./config:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE-NAME=postgres
      - DATABASE-USER=postgres
      - DATABASE-PASSWORD=postgres
      - DATABASE-HOST=database
      - DATABASE-PORT=5432
    depends_on:
      - redis
      - backend
    restart: on-failure

#  celery_stand_alone:
#    container_name: celery_stand_alone
#    image: celery_stand_alone
#    build:
#      context: ./celery_worker/
#      dockerfile: Dockerfile
#    command: sh -c "celery -A celery_base worker -l INFO -Q queue2"
#    volumes:
#      - ./celery_worker:/app
#    environment:
#      - BROKER_URL=redis://redis:6379/0
#      - RESULT_BACKEND=redis://redis:6379/0
#    depends_on:
#      - redis
#      - backend
#    restart: on-failure

volumes:
  database:
